labels:
  - name: bug
    color: d73a4a
    description: Something isn't working
  - name: documentation
    color: 0075ca
    description: Improvements or additions to documentation
  - name: duplicate
    color: cfd3d7
    description: This issue or pull request already exists
  - name: enhancement
    color: a2eeef
    description: New feature or request
  - name: good first issue
    color: 7057ff
    description: Good for newcomers
  - name: help wanted
    color: 008672
    description: Extra attention is needed
  - name: invalid
    color: e4e669
    description: This doesn't seem right
  - name: question
    color: d876e3
    description: Further information is requested
  - name: wontfix
    color: ffffff
    description: This will not be worked on
  - name: area: docs
    color: 0e8a16
    description: Documentation and guides
  - name: area: spec
    color: 1d76db
    description: Language specification
  - name: area: parser
    color: c2e0c6
    description: Parsing and syntax
  - name: area: interpreter
    color: fbca04
    description: Interpreter and runtime
  - name: area: typechecker
    color: 5319e7
    description: Type checker and typing
  - name: area: cli
    color: f9d0c4
    description: CLI and tooling
  - name: area: compiler
    color: 0f4c81
    description: Compiler and IR
  - name: area: tests
    color: bfe5bf
    description: Testing and CI
